/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scenes/Scene_loading.ls
 */
export class LoadingBase extends Laya.Scene {
    public loadingBar!: Laya.ProgressBar;
}

